services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"  # Оставляем, если нужен доступ к БД извне
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: calculator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sre_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d calculator"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build: ./auth_service
    networks:
      - sre_network  # Доступ только внутри Docker-сети

  calc_service:
    build: ./calc_service
    environment:
      - AUTH_URL=http://auth_service:5002/auth  # Внутренний адрес
      - HISTORY_URL=http://history_service:5003/history
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sre_network

  history_service:
    build: ./history_service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=calculator
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sre_network

networks:
  sre_network:
    driver: bridge

volumes:
  postgres_data: