global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "auth_service"
    static_configs:
      - targets: ["auth_service:5002"]
    metrics_path: /metrics

  - job_name: "calc_service"
    static_configs:
      - targets: ["calc_service:5001"]
    metrics_path: /metrics

  - job_name: "history_service"
    static_configs:
      - targets: ["history_service:5003"]
    metrics_path: /metrics