apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428  # Имя сервиса из docker-compose.yml
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      prometheusType: VictoriaMetrics
      timeInterval: 30s
    version: 1